CREATE TABLE GFE.IMAGES
(
  IMAGE_ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
  NAME NVARCHAR(50),
  DESCRIPTION NVARCHAR(400),
  FORMAT NVARCHAR (10),
  WIDTH INT,
  HEIGHT INT,
  URL NVARCHAR(400),
  IMAGE_BYTES BLOB
);
